const fs = require("node:fs");
const path = require("node:path");

const projectRoot = path.resolve(__dirname, "..");
const envPath = path.join(projectRoot, ".env");
const examplePath = path.join(projectRoot, ".env.example");
const outputPath = path.join(projectRoot, "miniprogram", "config", "env.ts");

function parseEnvironment(source) {
  const values = {};
  for (const rawLine of source.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) {
      continue;
    }

    const separator = line.indexOf("=");
    if (separator < 1) {
      continue;
    }

    const key = line.slice(0, separator).trim();
    let value = line.slice(separator + 1).trim();
    if (
      value.length >= 2 &&
      ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'")))
    ) {
      value = value.slice(1, -1);
    }
    values[key] = value;
  }
  return values;
}

const sourcePath = fs.existsSync(envPath) ? envPath : examplePath;
if (!fs.existsSync(sourcePath)) {
  throw new Error("缺少 frontend/.env 或 frontend/.env.example");
}

const environment = parseEnvironment(fs.readFileSync(sourcePath, "utf8"));
const miniProgramName = environment.MINIPROGRAM_NAME?.trim();
if (!miniProgramName) {
  throw new Error(`${path.basename(sourcePath)} 缺少 MINIPROGRAM_NAME`);
}

const output = `// This file is generated by scripts/generate-env.js from frontend/.env.\n// Do not edit it directly.\nexport const MINIPROGRAM_NAME = ${JSON.stringify(miniProgramName)};\n`;
const current = fs.existsSync(outputPath)
  ? fs.readFileSync(outputPath, "utf8")
  : "";
if (current !== output) {
  fs.writeFileSync(outputPath, output, "utf8");
  console.log(`Generated ${path.relative(projectRoot, outputPath)}.`);
}
